

select * 
   FROM DBPROD.SNIST_AUTO_RE SN
where  SN.DOCOR_SNIST  between '2010-01-10' and '2011-01-10'
whith ur; 


SELECT SN.NREG_SNIST_AUTO_RE
        ,SN.CPROT_SNIST 
        ,SN.CRAMO_SEGUR 
        ,SN.CSUCUR_SEGDR
        ,SN.CCIA_SEGDR 
        ,SN.VPREVT_DANO 
        ,SN.ISEGRD_AVISO_SNIST 
        ,SN.DOCOR_SNIST --date 2010-01-10
     FROM DBPROD.SNIST_AUTO_RE SN

     JOIN DBPROD.APOLC_SNIST A
       ON A.NREG_SNIST_AUTO_RE = SN.NREG_SNIST_AUTO_RE

     JOIN DBPROD.RAMO_CTBIL_SNIST_APOLC RC
       ON RC.NREG_SNIST_AUTO_RE = A.NREG_SNIST_AUTO_RE
      AND RC.NSEQ_APOLC_SNIST = A.NSEQ_APOLC_SNIST  

LEFT JOIN DBPROD.INFO_TECNC_SNIST_APOLC IT
         ON IT.NREG_SNIST_AUTO_RE = RC.NREG_SNIST_AUTO_RE
        AND IT.NSEQ_APOLC_SNIST = RC.NSEQ_APOLC_SNIST
        AND IT.CRAMO_SEGUR_CTBIL = RC.CRAMO_SEGUR_CTBIL
     --JOIN DBPROD.PSSOA_SNIST PS
     --  ON PS.CPSSOA_SNIST = SN.

 LEFT JOIN DBPROD.COMPL_APOLC_SNIST CA --(Tabela vai mudar o nome para COMPL_APOLC_SNIST)
       ON CA.NREG_SNIST_AUTO_RE = A.NREG_SNIST_AUTO_RE
       AND CA.NSEQ_APOLC_SNIST = A.NSEQ_APOLC_SNIST

  LEFT JOIN DBPROD.JUSTF_AUSEN_COMPL_SNIST JA --(Tabela vai mudar o nome para JUSTF_AUSEN_COMPL_APOLC_SNIST)      
        ON JA.NREG_SNIST_AUTO_RE = A.NREG_SNIST_AUTO_RE
       AND JA.NSEQ_APOLC_SNIST = A.NSEQ_APOLC_SNIST  

--OBS:Para Consulta é obrigatório apenas o preenchimento de um campo;3
    WHERE (SN.CPROT_SNIST is null or SN.CPROT_SNIST = 12)
     AND  (SN.NREG_SNIST_AUTO_RE is null or SN.NREG_SNIST_AUTO_RE = 100)
     AND SN.CRAMO_SEGUR = ?  --117
     AND SN.NAPOLC_SEGUR = ? 
     AND SN.DREG_SNIST = ? 
     AND SN.ISEGRD_AVISO_SNIST = ? 
     AND SN.DOCOR_SNIST = ? ---coloquei para teste de intervalo
     AND SN.DOCOR_SNIST  between '2010-01-10' and '2011-01-10'
 --OBS: Sinistros Com Complemento
    AND (CA.NREG_SNIST_AUTO_RE IS NOT NULL
    AND CA.NSEQ_APOLC_SNIST IS NOT NULL)
 --OBS: Sinistros Sem Complemento 
    AND (CA.NREG_SNIST_AUTO_RE IS NULL
    AND CA.NSEQ_APOLC_SNIST IS NULL)
--OBS: Sinistros Complementados com erro
    AND (JA.NREG_SNIST_AUTO_RE IS not NULL
    AND JA.NSEQ_APOLC_SNIST IS NOT NULL)
--OBS: Enviados para Técnica
    AND (IT.NREG_SNIST_AUTO_RE IS not NULL
    AND IT.NSEQ_APOLC_SNIST IS NOT NULL
    AND IT.CRAMO_SEGUR_CTBIL IS NOT null)
-- FETCH FIRST 100 ROWS ONLY
-- WITH UR 
;

ibge_code 


